modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="martinnico"
version="1.0.0"
displayName="Martin/Nico"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Owner, MCreator"

[[dependencies.martinnico]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.martinnico]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.martinnico]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

